/**
 * All available game scenes
 */
export enum SceneType {
  // System Scenes
  TITLE_SCREEN = 'TITLE_SCREEN',
  SYSTEM = 'SYSTEM',

  // Castle/Town Scenes
  CASTLE_MENU = 'CASTLE_MENU',
  TRAINING_GROUNDS = 'TRAINING_GROUNDS',
  TEMPLE = 'TEMPLE',
  SHOP = 'SHOP',
  TAVERN = 'TAVERN',
  INN = 'INN',
  CHARACTER_CREATION = 'CHARACTER_CREATION',
  CHARACTER_LIST = 'CHARACTER_LIST',
  CHARACTER_INSPECTION = 'CHARACTER_INSPECTION',

  // Dungeon Scenes
  MAZE = 'MAZE',
  COMBAT = 'COMBAT',
  CHEST = 'CHEST',
  CAMP = 'CAMP',

  // Maze Child Scenes (sub-routes of MAZE)
  MAZE_EXPLORATION = 'MAZE_EXPLORATION',
  MAZE_COMBAT_PLANNING = 'MAZE_COMBAT_PLANNING',
  MAZE_COMBAT_PLAYBACK = 'MAZE_COMBAT_PLAYBACK',
  MAZE_COMBAT_VICTORY = 'MAZE_COMBAT_VICTORY',
  MAZE_COMBAT_DEFEAT = 'MAZE_COMBAT_DEFEAT',
  MAZE_CHEST = 'MAZE_CHEST',
  MAZE_CHEST_PLAYBACK = 'MAZE_CHEST_PLAYBACK',
  MAZE_CHEST_REWARDS = 'MAZE_CHEST_REWARDS',
}
