/**
 * All available game scenes
 */
export enum SceneType {
  // System Scenes
  TITLE_SCREEN = 'TITLE_SCREEN',

  // Castle/Town Scenes
  CASTLE_MENU = 'CASTLE_MENU',
  TRAINING_GROUNDS = 'TRAINING_GROUNDS',
  TEMPLE = 'TEMPLE',
  SHOP = 'SHOP',
  TAVERN = 'TAVERN',
  INN = 'INN',
  CHARACTER_CREATION = 'CHARACTER_CREATION',
  CHARACTER_LIST = 'CHARACTER_LIST',
  CHARACTER_INSPECTION = 'CHARACTER_INSPECTION',

  // Dungeon Scenes
  MAZE = 'MAZE',
  COMBAT = 'COMBAT',
  CHEST = 'CHEST',
}
